COMP: Expand slice set assignment
Avoids

Wrapping/Modules/MorphologicalContourInterpolation/itkMorphologicalContourInterpolatorPython.cpp:7347:105:
required from here
../../include/itkMorphologicalContourInterpolator.h:185:34: error: no match
for ‘operator=’ (operand types are ‘std::set<long int, std::less<long int>,
std::allocator<long int> >’ and ‘void’)
     m_LabeledSlices[axis][label] = SliceSetType().insert( indices.begin(),
     indices.end() );

with Clang and GCC on Linux.